### ISSUE TITLE
 Request for Update on "Kingdom Two Crowns"Mod

### ISSUE THREAD

**Issue by Zaykus** [abevol/KingdomMod#12]
**Subject:** Request for Update on "Kingdom Two Crowns"Mod so it can run with the last update 
---
Hi **abevol** 

I hope you're doing well. I wanted to reach out regarding the "Kingdom Two Crowns" Mod (https://github.com/abevol/KingdomMod). It appears that the Mod may be outdated, as I'm running into some compatibility issues with the latest version of the game.

Would it be possible for you to update the Mod to ensure it works smoothly with the current version of *_Kingdom Two Crowns: Call Of Olympus dlc_*? It's an amazing mod, and I'd love to continue using it with the latest updates.

Thank you for all your hard work on this project. I really appreciate your time and effort!

Best regards,  
Zaykus.

**Comment by abevol** [comment]
Version 2.3.0 has been released. 
Preliminary testing shows no problems. 
If there are any problems, please provide feedback.

[KingdomMod/releases/tag/2.3.0](https://github.com/abevol/KingdomMod/releases/tag/2.3.0)

**Comment by Zaykus** [comment]
> Version 2.3.0 has been released. 
> Preliminary testing shows no problems. 
> If there are any problems, please provide feedback.
> 
> [KingdomMod/releases/tag/2.3.0](https://github.com/abevol/KingdomMod/releases/tag/2.3.0)

Awesome testing right now
