### ISSUE TITLE
Map Overlay Mod does not work for me

### ISSUE THREAD

**Issue by Runkel79** [abevol/KingdomMod#13]
If i use the linked BepInEx Version from the install section (BepInEx-Unity.Mono-win-x86-6.0.0-be.670) nothing happens, no BepInEx window opens.

If i use the Mono x64 Version from https://github.com/bepinex/bepinex/releases the BepInEx Window opens and the installed Mods load

I have the Stamina Bar and the Overlay Map Mod installed.

- The Stamina Bar mod works great.

The Map Overlay Mod has following errors (I also attached a Screenshot):

- Overlay Map is not rendered
- Peasant are not counted
- Workers are not counted
- Farmer are not counted
- Farmland is not counted

The BepInEx window that opens spams the following red error message (That file path doesn't look right): 

`[Error  : Unity Log] NullReferenceException: Property not exist.
Stack trace:
KingdomMod.ObjectExtensions.GetPropertyValue[TR] (System.Object this, System.String prop) (at D:/workspace/games/KingdomTwoCrowns/KingdomMapMod/Shared/ObjectExtensions.cs:173)
KingdomMod.OverlayMap.UpdateMinimapMarkList () (at D:/workspace/games/KingdomTwoCrowns/KingdomMapMod/OverlayMap/OverlayMap.cs:512)
KingdomMod.OverlayMap.Update () (at D:/workspace/games/KingdomTwoCrowns/KingdomMapMod/OverlayMap/OverlayMap.cs:168)`

And here is the LogOutput.log:

`[Message: Preloader] BepInEx 6.0.0-be.697 - KingdomTwoCrowns
[Message: Preloader] Built from commit 53625800b86f6c68751445248260edf0b27a71c2
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   : Preloader] Running under Unity 2022.3.32f1
[Info   : Preloader] CLR runtime version: 4.0.30319.42000
[Info   : Preloader] Supports SRE: True
[Message: Preloader] Preloader started
[Info   :AssemblyPatcher] Loaded 1 patcher type from [BepInEx.Unity.Mono.Preloader 6.0.0.0]
[Info   : Preloader] 1 patcher plugin loaded
[Info   : Preloader] 166 assemblies discovered
[Message:AssemblyPatcher] Executing 1 patch(es)
[Message: Preloader] Preloader finished
[Message:   BepInEx] Chainloader initialized
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [KingdomMod.OverlayMap 2.3.0]
[Info   :KingdomMod.OverlayMap] Plugin KingdomMod.OverlayMap is loaded!
[Message:KingdomMod.OverlayMap] [142][ConfigBind] ConfigBind: KingdomMod.OverlayMap.cfg
[Message:KingdomMod.OverlayMap] [108][Initialize] Config prefab file: C:\Program Files (x86)\Steam\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.Style.cfg
[Message:KingdomMod.OverlayMap] [108][Initialize] Config prefab file: C:\Program Files (x86)\Steam\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.Language.en-US.cfg
[Message:KingdomMod.OverlayMap] [108][Initialize] Config prefab file: C:\Program Files (x86)\Steam\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.Language.zh-CN.cfg
[Message:KingdomMod.OverlayMap] [154][ConfigBind] ConfigFilePath: C:\Program Files (x86)\Steam\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.cfg
[Message:KingdomMod.OverlayMap] [155][ConfigBind] Language: system
[Message:KingdomMod.OverlayMap] [156][ConfigBind] StyleFile: KingdomMod.OverlayMap.Style.cfg
[Message:KingdomMod.OverlayMap] [157][ConfigBind] GUIUpdatesPerSecond: 10
[Message:KingdomMod.OverlayMap] [159][ConfigBind] Loaded config: KingdomMod.OverlayMap.cfg
[Message:KingdomMod.OverlayMap] [190][OnLanguageChanged] OnLanguageChanged: system
[Message:KingdomMod.OverlayMap] [198][OnLanguageChanged] Language file: C:\Program Files (x86)\Steam\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.Language.de-DE.cfg
[Warning:KingdomMod.OverlayMap] Language file do not exist: C:\Program Files (x86)\Steam\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.Language.de-DE.cfg
[Warning:KingdomMod.OverlayMap] Language file do not exist: C:\Program Files (x86)\Steam\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.Language.de-DE.cfg
[Warning:KingdomMod.OverlayMap] Try to use the default english language file: C:\Program Files (x86)\Steam\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.Language.en-US.cfg
[Message:KingdomMod.OverlayMap] [235][OnLanguageChanged] Try to bind Language file: KingdomMod.OverlayMap.Language.en-US.cfg
[Message:KingdomMod.OverlayMap] [400][ConfigBind] ConfigBind: KingdomMod.OverlayMap.Language.en-US.cfg
[Message:KingdomMod.OverlayMap] [501][ConfigBind] Loaded config: KingdomMod.OverlayMap.Language.en-US.cfg
[Message:KingdomMod.OverlayMap] [241][OnStyleFileChanged] OnStyleFileChanged: KingdomMod.OverlayMap.Style.cfg
[Message:KingdomMod.OverlayMap] [245][OnStyleFileChanged] Style file: C:\Program Files (x86)\Steam\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.Style.cfg
[Message:KingdomMod.OverlayMap] [265][OnStyleFileChanged] Try to bind style file: KingdomMod.OverlayMap.Style.cfg
[Message:KingdomMod.OverlayMap] [594][ConfigBind] ConfigBind: KingdomMod.OverlayMap.Style.cfg
[Message:KingdomMod.OverlayMap] [737][ConfigBind] Loaded config: KingdomMod.OverlayMap.Style.cfg
[Info   :   BepInEx] Loading [KingdomMod.StaminaBar 2.3.0]
[Info   :KingdomMod.StaminaBar] Plugin KingdomMod.StaminaBar is loaded!
[Message:   BepInEx] Chainloader startup complete
[Info   :   Console] Successfully Loaded Haglet Assemblies
[Message:KingdomMod.OverlayMap] OverlayMap Start.
[Message:KingdomMod.StaminaBar] StaminaBar Start.
[Message:KingdomMod.OverlayMap] OnGameStart.
[Message:KingdomMod.OverlayMap] OnGameStart: _archiveFilename island-v35-c4-l9, Campaign 4, CurrentLand 9, currentChallenge 0
[Message:KingdomMod.OverlayMap] [283][ConfigBind] ExploredRegions file: C:\Program Files (x86)\Steam\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.ExploredRegions.cfg
[Message:KingdomMod.OverlayMap] [294][ConfigBind] Loaded config: KingdomMod.OverlayMap.ExploredRegions.cfg
[Message:KingdomMod.OverlayMap] OnGameStart.
[Message:KingdomMod.OverlayMap] OnGameStart: _archiveFilename island-v35-c0-l2, Campaign 0, CurrentLand 2, currentChallenge 0
[Message:KingdomMod.OverlayMap] [283][ConfigBind] ExploredRegions file: C:\Program Files (x86)\Steam\steamapps\common\Kingdom Two Crowns\BepInEx\config\KingdomMod.OverlayMap.ExploredRegions.cfg
[Message:KingdomMod.OverlayMap] [294][ConfigBind] Loaded config: KingdomMod.OverlayMap.ExploredRegions.cfg
`

![KingdomTwoCrowns_lYLukB18t2](https://github.com/user-attachments/assets/f8584125-ea47-483e-8bfe-7320be1d5c85)

**Comment by abevol** [comment]
I need to take a look at the red logs in your game console window.

**Comment by abevol** [comment]
It's fixed now, pls test it.

https://github.com/abevol/KingdomMod/releases/tag/2.3.1

**Comment by Runkel79** [comment]
Sorry for the late reply.

Now it's working. Thanks a lot! 🥇
