### ISSUE TITLE
Mod Not Appearing in Game or Not loaded -  G/Version 2.0.1 (R21960)

### ISSUE THREAD

**Issue by Zaykus** [abevol/KingdomMod#14]
### KingdomMod v2.3.0 Issues

Hi @abevol ,

_Thx for #12_ 

**I recently tried installing the KingdomMod but I'm encountering an issue where the mod simply doesn't appear in the game. I have ensured that all files are placed correctly as per the installation instructions. My game version is 2.0.1 (R21960).** 

Steps I’ve taken:

_1. Downloaded and placed the mod files in the correct directory.
2. Verified the game version and mod compatibility.
3. Checked for any conflicts or missing files._

![Screenshot 2024-10-13 222429](https://github.com/user-attachments/assets/cca93099-3162-412c-b23a-ce7087f7ef33)
![Screenshot 2024-10-13 222446](https://github.com/user-attachments/assets/b336f90d-f31d-43f8-8543-876cda9309a7)
![Screenshot 2024-10-13 222510](https://github.com/user-attachments/assets/37c79493-fd87-4b10-b98f-a4ef92d526ab)

Despite following the steps, the mod doesn't show up or function in the game. Is there an update or something specific I need to do to get it working with my game version?

Any assistance would be greatly appreciated.

Thank you!

zaykus

**Comment by abevol** [comment]
You need to install the latest version of BepInEx. 
I have updated the download address in Readme.md. 
Please download and install it again. (BTW, you need to install the Mono version.)

**Comment by Zaykus** [comment]
I also tried to update the files from the README folder, but this was before it was updated. I have now updated the game to version 2.0.2, so all requirements are set, I’m currently testing the mod. Thanks for the help.
Zaykus.
![Screenshot 2024-10-13 230936](https://github.com/user-attachments/assets/e0d67052-9902-49ad-9b62-3ff49277a6ef)

**Comment by Zaykus** [comment]
- [x] Worked!

Hi,

I’ve been testing the mod with different versions of the game. Unfortunately, version 2.0.2 didn’t work – maybe the crack is bad, who knows! However, **I did get it to work with version 2.0.1.**

If you need, I can upload the log files for your review.
[LogOutput.log](https://github.com/user-attachments/files/17357088/LogOutput.log)


- [ ] I’m considering modifying the code to enhance the interface, look, and UI – just a heads up.

Thanks for all your help!

zaykus.

**Comment by abevol** [comment]
> version 2.0.2 didn’t work

In fact, I made it based on the latest version of the game, which is version 2.0.2. In theory, it should works well.
No obvious abnormalities were found in the log file you provided.

>  I’m considering modifying the code to enhance the interface, look, and UI

Looking forward to your contribution.

**Comment by Zaykus** [comment]
> > version 2.0.2 didn’t work
> 
> In fact, I made it based on the latest version of the game, which is version 2.0.2. In theory, it should works well.
gog crack contains many modifications, including a special player "exe file", not the regular one. 

> No obvious abnormalities were found in the log file you provided.
> 
That's great I think 🐣

> >  I’m considering modifying the code to enhance the interface, look, and UI
> 
> Looking forward to your contribution.

Don't overthink it, I use libraries and AI to do the code side lol.

Best regards,
Zaykus.
