### ISSUE TITLE
Separate mod for the purse enhancement

### ISSUE THREAD

**Issue by At0ku** [abevol/KingdomMod#17]
Hello. 

Thanks you for the updated mod. Can I ask you if is it possible to create a separate mod that only contain the purse enhancement and not the BetterPayableUpgrade ?

"Adjust details
Reduced the size of the coin, now your coin bag can hold more coins (about 100)."

Well I'm not an expert but with DNspy I simply try to replace "nop" by "ret" in HandlePayable using "Edit Method Body" on the first line, it seems to do the trick.

**Comment by Zaykus** [comment]
Hi @At0ku,

You can manage the modifications individually by yourself. Simply enter the folder `_Kingdom Two Crowns\BepInEx\plugins_` and remove the specific mods you want to exclude. This should help you achieve the setup you're looking for.

# Or,
if you want to add options to 
- [ ] disable
- [x] enable
mods directly from within the game, submit a request in this regard.

Best regards,  
zaykus
