### ISSUE TITLE
地图模组无法使用，耐力条倒是可以

### ISSUE THREAD

**Issue by juggernaught114514** [abevol/KingdomMod#18]
报错代码，用的是最新的，都是照着教程走的

[Error  : Unity Log] DirectoryNotFoundException: Could not find a part of the path "F:\SteamLibrary\steamapps\common\Kingdom Two Crowns\config\KingdomMod.OverlayMap.Style.cfg".
Stack trace:
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) (at <467a840a914a47078e4ae9b0b1e8779e>:0)
System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options) (at <467a840a914a47078e4ae9b0b1e8779e>:0)
(wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions)
System.IO.StreamWriter..ctor (System.String path, System.Boolean append, System.Text.Encoding encoding, System.Int32 bufferSize) (at <467a840a914a47078e4ae9b0b1e8779e>:0)
System.IO.StreamWriter..ctor (System.String path) (at <467a840a914a47078e4ae9b0b1e8779e>:0)
(wrapper remoting-invoke-with-check) System.IO.StreamWriter..ctor(string)
System.IO.File.WriteAllText (System.String path, System.String contents) (at <467a840a914a47078e4ae9b0b1e8779e>:0)
KingdomMod.OverlayMap+Config+ConfigPrefabs.Initialize () (at D:/workspace/games/KingdomTwoCrowns/KingdomMapMod/OverlayMap/OverlayMap.Config.cs:114)
KingdomMod.OverlayMap+Config+Global.ConfigBind (BepInEx.Configuration.ConfigFile config) (at D:/workspace/games/KingdomTwoCrowns/KingdomMapMod/OverlayMap/OverlayMap.Config.cs:144)
KingdomMod.OverlayMap.Initialize (KingdomMod.OverlayMapPlugin plugin) (at D:/workspace/games/KingdomTwoCrowns/KingdomMapMod/OverlayMap/OverlayMap.cs:82)
KingdomMod.OverlayMapPlugin.Init () (at D:/workspace/games/KingdomTwoCrowns/KingdomMapMod/OverlayMap/OverlayMapPlugin.cs:64)
KingdomMod.OverlayMapPlugin.Awake () (at D:/workspace/games/KingdomTwoCrowns/KingdomMapMod/OverlayMap/OverlayMapPlugin.cs:41)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Unity.Mono.Bootstrap.UnityChainloader:LoadPlugin(PluginInfo, Assembly) (at /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.Mono/Bootstrap/UnityChainloader.cs:143)
BepInEx.Bootstrap.BaseChainloader`1:LoadPlugins(IList`1) (at /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Bootstrap/BaseChainloader.cs:411)
BepInEx.Bootstrap.BaseChainloader`1:Execute() (at /home/runner/work/BepInEx/BepInEx/BepInEx.Core/Bootstrap/BaseChainloader.cs:317)
BepInEx.Unity.Mono.Bootstrap.UnityChainloader:StaticStart(String) (at /home/runner/work/BepInEx/BepInEx/Runtimes/Unity/BepInEx.Unity.Mono/Bootstrap/UnityChainloader.cs:75)
UnityEngine.Application:.cctor()
Rewired.InputManager_Base:Awake()

**Comment by abevol** [comment]
应该是插件放置的位置不对，完整的路径应该是这样的：
D:\SteamLibrary\steamapps\common\Kingdom Two Crowns\BepInEx\plugins\KingdomMod.OverlayMap\KingdomMod.OverlayMap.dll

请参考上面的路径提示，按照项目主页的安装教程，再安装一遍 BepInEx 和本项目的模组。
