### ISSUE TITLE
Kingdom Eighties Support

### ISSUE THREAD

**Issue by syberphunk** [abevol/KingdomMod#2]
Can this be updated to work with Kingdom Eighties?

**Comment by abevol** [comment]
虽然技术上没有问题，但是由于个人原因，我实在不喜欢《王国：80年代》，目前也没有购买该游戏。
因此，很可能不会制作《王国：80年代》的适配版本。
While technically fine, for personal reasons I really don't like "Kingdoms Eighties" and haven't bought the game yet. 
As such, it's likely that an adaptation of "Kingdoms Eighties" won't be made.
