### ISSUE TITLE
Cannot load mods

### ISSUE THREAD

**Issue by mrsezer** [abevol/KingdomMod#4]
![photo](https://github.com/abevol/KingdomMod/assets/66494324/1263ca83-3b7e-4f2c-b866-8123d209d7b6)

i did all things but when i open game its just normal there is no console to load mods what should i do?

**Comment by abevol** [comment]
According to information provided by users on the nexusmods forum, there are differences between the versions of the game in the West and Asia. The Asian version is il2cpp, while the Western version is mono, so the mod may not work with your locally installed version of the game ( mono version). I'll try to fix this when I have time.
