### ISSUE TITLE
Explored area is forgoten after traveling

### ISSUE THREAD

**Issue by CamiloCastelo** [abevol/KingdomMod#5]
I was so happy when I found this mod could do this:

_"By default, only the markers in the area you have explored are displayed"_

Kingdom could finally have a map that takes note of what I've found, so I don't have to remember the position of everything when I go back to the 2nd island, after having passed by the 3rd, 4th, and 5th, right?

No. Unfortunately, when I go back to a previous island, the mod simply forgets the area I have explored there, and starts tracking the spots again as if I were scouting that island for the first time. For me, this defeats the main purpose of this mod.

_"of course you can also show the full map immediately by pressing the F key"_

I could do that when going back to an island, but I don't want to, because many times I travel from an island having explored only parts of it. So I don't want to go back there and activate the full map, as if I had explored everything.

Isn't possible for this mod to remember the explored are after traveling?

If not, it's OK. This is certainly a good mod for many other players.

**Comment by abevol** [comment]
I have considered your idea at the time. To implement it, I need to intervene in the game's archive. 
This is currently a challenge for me, but I believe I will implement it in the future. 
Thanks for your suggestions and feedback!
