### ISSUE TITLE
Mods fail to load properly*

### ISSUE THREAD

**Issue by VaelophisNyx** [abevol/KingdomMod#9]
When attempting to use StaminaBar specifically, the log file shows that BepInEx patches IL2CPP properly, loads the plugin, then the console closes and the game relaunches without any mods enabled. This happens with any version of BepInEx for IL2CPP, even new nightly builds

**Comment by VaelophisNyx** [comment]
To clarify further, I looked at the log file (with a lot of BepInEx log file inspection from other games) and there are 0 errors

**Comment by abevol** [comment]
Please try the latest version. If the problem still exists, please open a new issue.
